// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC8WURCrLAQIBxhf_9Mv2aJuqyEHIf4Hk',
    appId: '1:499111016019:android:a1a62cee611dc53171b8a6',
    messagingSenderId: '499111016019',
    projectId: 'sahyadri-explorer-b9c7d',
    storageBucket: 'sahyadri-explorer-b9c7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUbbtXgaAwbhFWdFqLKrSi3PLrdEDo5hI',
    appId: '1:499111016019:ios:d47013fe90b5391a71b8a6',
    messagingSenderId: '499111016019',
    projectId: 'sahyadri-explorer-b9c7d',
    storageBucket: 'sahyadri-explorer-b9c7d.firebasestorage.app',
    androidClientId: '499111016019-d2io91pigjk8rgnciu9n089mf6aikkis.apps.googleusercontent.com',
    iosClientId: '499111016019-e4upqtb076sel0tugugm5flftsegalf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sahyadriExplorer',
  );

}